"""Declarative base for future SQLAlchemy models.

No models are defined in T03 — this only stands up the `Base` class and a
naming convention for constraints/indexes, so Alembic autogenerate (used
by later migrations, per the technical spec's greenfield initial
migration) produces stable, predictable constraint names instead of
SQLAlchemy's opaque defaults.

Per the frozen database design, primary keys are UUIDv7 values generated
application-side (e.g. via `uuid6`) — never a Postgres `DEFAULT` — so no
server-side id default is wired here or will be in future models.
"""

from __future__ import annotations

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# Explicit naming convention so autogenerated constraint/index names are
# deterministic across environments and diffable in migration files.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Shared declarative base for all future ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)
